version: '3'

services:
  api:
    container_name: "jibberjabber-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: jibberjabber-db
      DB_HOST: db
      DB_PORT: 5432
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080
      FOLLOWERS_HOST: followers-api
      FOLLOWERS_PORT: 8083

  followers-api:
    container_name: "followers-api"
    image: ghcr.io/agustinvon/jibberjabberfollowers-dev:latest
    ports:
      - "8083:8083"
    environment:
      DB_HOST: follower-db
      DB_PORT: 5432
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080
    depends_on:
      - follower-db

  db:
    container_name: postgre-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jibberjabber-db

  follower-db:
    container_name: follower-db
    image: postgres:12
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jibberjabber-db

  db-keycloak:
    image: postgres:12
    container_name: pgdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgdb

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=pgdb
      - KC_DB_URL_DATABASE=pgdb
      - KC_DB_USERNAME=sa
      - KC_DB_PASSWORD=password
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - db-keycloak
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"

volumes:
  pgdata:
    external: true