version: '3'

services:
  api:
    container_name: "jibberjabber-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: jibberjabber-db
      DB_HOST: postgre-db
      DB_PORT: 5432

  db:
    container_name: postgre-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jibberjabber-db

  db-keycloak:
    image: postgres:12
    container_name: pgdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgdb

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=pgdb
      - KC_DB_URL_DATABASE=pgdb
      - KC_DB_USERNAME=sa
      - KC_DB_PASSWORD=password
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - db-keycloak
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"

volumes:
  pgdata:
    external: true